blank_issues_enabled: true
contact_links:
  - name: Contribution Guide
    url: https://github.com/henderson-01/Alien_Invasion/blob/main/CONTRIBUTING.md
    about: Read the contributing guide before opening an issue or pull request.